#!/usr/bin/env bash

##
# Usage:
#   run-java [all parameters you would use with normal java]
##

##
# Example:
#   run-java example.Hello
##

##
# Grab JVM_OPTS from environment variable
##
JVM_OPTS=${JVM_OPTS:=}

##
# All wrapper parameters will be as well java parameters
# (keep in mind that this will contains docker entrypoint and cmd)
##
ENTRYPOINT="$@"

##
# Finally run pure java
##
exec java ${JVM_OPTS} ${ENTRYPOINT} 